name: Actions Workflow
on:          # commented out to prevent github from running these actions and hitting usage limits.
  #push:  
  #pull_request:
  #  types: [closed,opened,assigned,reopened]
  #schedule:
  #  - cron: "* * 1 1-6 *" #https://crontab.guru/
  #  - cron: "0 22 * * MON-FRI"
  repository_dispatch:    # uses a webhook, called repositary_dispatch, an external post request is needed to trigger this. 
    types: [lock]  # send post request to url with this event_type as body of post. This request can have a payload too which can be read.
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload_read       # Reads the variables passed in client_payload in the body of post request for repositary_dispatch api. 
        run: |     
          echo ${{ github.event.client_payload.env }}  
          echo ${{ github.event.client_payload.name }}   
          echo ${{ github.event.client_payload.purpose }}    
      - name: List files
        run: |
          pwd
          ls -lah
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: checkout
        uses: actions/checkout@v3
      - name: List files after checkout
        run: |
          pwd
          ls -lah
      - name: Simple Java Script Action
        id: greet   # id is needed to reference any step
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'BRK the UberCoder'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}" # in order to reference a step we need its ID