name: Shell Commands # name of the workflow
on: [pull_request]    # event on which workflow should trigger
jobs:         # each worklow can have one or more jobs. Key for each job is name of the job.
  run-shell-command:         # each job is an object as well with bunch of keys
    runs-on: ubuntu-latest   # Each job runs on a seperate VM, the OS is defined here.
    steps:                   # steps is array of object, each object is a step
      - name: echo a string
        run: echo "BRK is the king"
      - name: multiline script    #name of the step
        run: |         # Multi line command so using pipe symbol
          node -v
          npm -v
      - name: python Commands
        run: |
          import random
          for x in range(1,10):
            print(random.randint(0,9)) 
        shell: python   # this informs that this command should be run on python.
  run-windows-commands:    # runs in parallel with run-shell-command job
    runs-on: windows-latest
    steps:
      - name: Directory from Powershell   
        run: Get-Location      # Runs Powershell as this is default shell
      - name: Pwd from shell running in windows
        run: pwd
        shell: bash         # This tells the runner to use bash shell

  run-shell-two-command:
    runs-on: ubuntu-latest
    needs: ["run-shell-command"]
    steps:
      - name: get OS
        run: cat /etc/os-release

