name: Shell Commands # name of the workflow
on: [push]    # event on which workflow should trigger
jobs:         # each worklow can have one or more jobs. Key for each job is name of the job.
  run-shell-command:         # each job is an object as well with bunch of keys
    runs-on: ubuntu-latest   # Each job runs on a seperate VM, the OS is defined here.
    steps:                   # steps is array of object, each object is a step
      - name: echo a string
        run: echo "BRK is the king"
      - name: multiline script
        run: |
          node -v
          npm -v

